name: Build

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.9]

    #if: startsWith(github.event.head_commit.message, 'Release')
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cffi>=1.0 pytest wheel
      - name: Build Wheels
        env:
          CIBW_ARCHS: "auto64"
          CIBW_SKIP: "cp36-* cp37-* cp312-*"
        run: |
          python -m pip install cibuildwheel
          python -m cibuildwheel --output-dir wheelhouse
      - name: Run Tests
        run: |
          python_version_tag=cp${{ matrix.python-version }}-cp${{ matrix.python-version }}*
          platform_tag=$(if [ "${{ matrix.os }}" = "windows-latest" ]; then echo "win_amd64"; else echo "manylinux_x86_64"; fi)
          wheel_to_install=$(ls wheelhouse/*$python_version_tag*$platform_tag.whl)
          pip install $wheel_to_install
          pytest
      - name: Save Wheels
        uses: actions/upload-artifact@v3
        with:
          name: wheels
          path: ./wheelhouse/*.whl
